import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFileSync} from 'node:child_process';
const out=process.env.LORE_SCREENSHOT_DIR||join(tmpdir(),'nopas-lore-review');await mkdir(out,{recursive:true});const b=await chromium.launch();const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));assert.equal((await p.goto('http://127.0.0.1:4321/lore/',{waitUntil:'networkidle'})).status(),200);await p.evaluate(()=>document.fonts.ready);
assert.equal(await p.locator('.lore-chapters li').count(),12);assert.equal(await p.locator('.lore-chapter').count(),12);assert.equal(await p.locator('.lore-document').count(),5);assert.equal(await p.locator('#timeline ol li').count(),16);assert.equal(await p.locator('#glossary dt').count(),14);
const old=execFileSync('git',['show','HEAD:src/pages/lore/index.astro'],{encoding:'utf8'});const headings=[...old.matchAll(/<h[23][^>]*>([\s\S]*?)<\/h[23]>/g)].map(m=>m[1]);assert.deepEqual(await p.evaluate(hs=>{const text=document.querySelector('.lore-page').textContent.replace(/\s+/g,' ').trim();return hs.map(h=>{const e=document.createElement('div');e.innerHTML=h;return e.textContent.replace(/\s+/g,' ').trim()}).filter(h=>!text.includes(h));},headings),[]);
for(const width of [320,390,768,1024,1440]){await p.setViewportSize({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+width);assert.deepEqual(await p.locator('.lore-page h1,.lore-page h2,.lore-page h3').evaluateAll(es=>es.filter(e=>e.scrollWidth>e.clientWidth+2).map(e=>e.textContent)),[],'heading fit '+width);}
for(const d of await p.locator('.lore-document').all()){await d.locator('summary').focus();await p.keyboard.press('Enter');assert.equal(await d.evaluate(e=>e.open),true);await p.keyboard.press('Enter');assert.equal(await d.evaluate(e=>e.open),false);}
for(const a of await p.locator('.lore-chapters li a').all()){await a.click();assert.equal(await p.evaluate(()=>!!document.getElementById(location.hash.slice(1))),true);}
const links=await p.locator('.lore-page a[href^="/"]').evaluateAll(es=>[...new Set(es.map(e=>e.getAttribute('href')))]);for(const href of links)assert.equal((await p.request.get('http://127.0.0.1:4321'+href)).status(),200,href);
await p.locator('.lore-page img').evaluateAll(es=>Promise.all(es.map(e=>{e.loading='eager';return e.decode()})));assert.equal(await p.locator('img[src*="lore-know-your-enemy"]').count(),0);assert.match(await p.locator('.lore-enemy').innerText(),/Defender insult/);
for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:join(out,`lore-${name}.png`),fullPage:true,style:'astro-dev-toolbar{display:none!important}'});await p.screenshot({path:join(out,`lore-${name}-top.png`),style:'astro-dev-toolbar{display:none!important}'});for(const [part,selector] of [['updf','#updf'],['updf-image','#updf > figure:first-of-type'],['enemy','.lore-enemy'],['origin','#origin'],['glossary','#glossary']])await p.locator(selector).screenshot({path:join(out,`lore-${part}-${name}.png`),style:'header,astro-dev-toolbar{visibility:hidden!important}'});}
await p.locator('.lore-document').first().evaluate(e=>e.open=true);await p.locator('.lore-document').first().screenshot({path:join(out,'lore-document-mobile.png'),style:'header,astro-dev-toolbar{visibility:hidden!important}'});
await p.getByRole('button',{name:'Open menu',exact:true}).click();assert.equal(await p.locator('#mobile-menu-toggle').getAttribute('aria-expanded'),'true');await p.getByRole('button',{name:'Close menu',exact:true}).click();assert.deepEqual(errors,[]);console.log('PASS: five widths, twelve chapters/anchors, five keyboard disclosures, original headings,16 timeline entries,14 glossary terms, local links, images, canon replacement, mobile menu, no page errors. '+out);await b.close();
